### ISSUE TITLE
Error when connecting to R server

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal-datasource-redcap#5]
Nothing to do with R, but with unresolved/conflicting deps instead.

```
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_181]
	... 80 common frames omitted
```

**Comment by kazoompa** [comment]
I did change the version (2.8.1) and still there is an exception when trying to connect to R. The _jackson-dataformat-xml_ is the one library used by REDCap plugin and not used by Opal by default. Needs more investigation.
